# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEdit_StringInput = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_StringInput.setFont(font)
        self.lineEdit_StringInput.setObjectName("lineEdit_StringInput")
        self.horizontalLayout.addWidget(self.lineEdit_StringInput)
        self.pushButton_ParseInput = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_ParseInput.setFont(font)
        self.pushButton_ParseInput.setObjectName("pushButton_ParseInput")
        self.horizontalLayout.addWidget(self.pushButton_ParseInput)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.textBrowser_Log = QtWidgets.QTextBrowser(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_Log.sizePolicy().hasHeightForWidth())
        self.textBrowser_Log.setSizePolicy(sizePolicy)
        self.textBrowser_Log.setMinimumSize(QtCore.QSize(0, 0))
        self.textBrowser_Log.setBaseSize(QtCore.QSize(0, 0))
        self.textBrowser_Log.setObjectName("textBrowser_Log")
        self.verticalLayout_2.addWidget(self.textBrowser_Log)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.tableWidget_LexemasOut = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_LexemasOut.setRowCount(0)
        self.tableWidget_LexemasOut.setColumnCount(3)
        self.tableWidget_LexemasOut.setObjectName("tableWidget_LexemasOut")
        self.tableWidget_LexemasOut.verticalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.tableWidget_LexemasOut)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.lineEdit_LexemaOut = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_LexemaOut.setReadOnly(True)
        self.lineEdit_LexemaOut.setObjectName("lineEdit_LexemaOut")
        self.horizontalLayout_2.addWidget(self.lineEdit_LexemaOut)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Лексический анализатор"))
        self.label_2.setText(_translate("MainWindow", "Строка для разбора:"))
        self.pushButton_ParseInput.setText(_translate("MainWindow", "Разобрать"))
        self.label_4.setText(_translate("MainWindow", "Лог"))
        self.label_3.setText(_translate("MainWindow", "Таблица лексем:"))
        self.label_5.setText(_translate("MainWindow", "Последовательность лексем:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
